### PR TITLE
Update dlm_data_parser.c

### LINKED ISSUE #2: Change the CSV converter to keep the output same name as the input file
Right now the csv converter requires an input and an output file. Change this so the output file is just "input_file.gdat.csv". Look at the ld converter as that is how that program works

### PR DESCRIPTION
**Pull request by pyagnik1**
updated the file name for csv_file

### CODE REVIEW

**Comment by pyagnik1** [comment]
Hello @caljay98 I have updated file I/O to write the data to "input_file.gdat.csv". Thank you for the opportunity, I really appreciate it. Please let me know if I can improve my contributions.

**Comment by caljay98** [comment]
I don't think you fully understand what needs to be modified. Currently the csv converter takes in two input arguments, an input file and an output file.

We need this program to take in a single argument, the input file, just like it already does. The output file will be the same name as the input file, only with the string ".csv" appended to it.

Apologies if the details on the ticket were not very clear

**Comment by pyagnik1** [comment]
Hi, thanks for the feedback, I have edited the code based on your specification. Now when you compile the dlm_data_parser.c you can type the file name itself, the code will append an appropriate extension to the file name. When compiling just write input instead of input.gdat.

**Comment by pyagnik1** [comment]
I am a noob so please disregard my coding abilities. 😅

**Comment by pyagnik1** [comment]
I looked at the gdat to ld and made changes to the dlm_data_parser.c. Please let me know if there is anything else I can do. Thanks again for the opportunity 🙏 I really appreciate it.

**Review by caljay98 — APPROVED** [review]
This what I was looking for. Thanks for your help!

**Pull request merged**
