### PR TITLE
Filter Outliers

### LINKED ISSUE #3: Remove extraneous data points when converting to .ld data
In its current state, the DLM occasionally writes a data point that is completely wrong. These are annoying when viewing data as the mess with the minimum and maximum scaling. Find a good algorithm to detect those data points and remove them from the .ld data

### PR DESCRIPTION
**Pull request by olale013**
Fixes #3

* Added filter_outliers to remove unexpected extreme changes in data
* A datapoint is replaced by the previous value if:
  * % change from previous value is > 100%
  * And previous value is nonzero
  * And next value is > 100 (prevents removing data like current gear / shifter position)
* Also removes the first value of each channel
  * For some reason was inaccurate in several channels, affecting auto scaling
 
Before:
before

After:
after

### CODE REVIEW

**Comment by AlexT2052** [comment]
Tested on a few datasets and works well, awesome it removes the scaling issue. I did find 2 instances where it didn't remove an outlier point because the outlier wasn't over 100% difference, but was over 90%. When I tried to test changing it it didn't work on my computer, but I doubt changing it to 90 would harm anything else.

**Comment by olale013** [comment]
Thanks for trying it out. Could you share which channels you found? The conditions aren't very concrete, just whatever works best.

**Comment by AlexT2052** [comment]
Sure, heres those 2 instances, they are just a single point, for the differences in the multicolored geared rpms, which originate in the cyan RPM reading in the bottom. The RPM reading looks like a triangle because of something motec is doing on that line for some reason, as when I press s it shows it really is only 1 out of place point. As you can see the difference in the values of each of these lines between regular and outlier is under 100%, but not too far under it.
Screenshot 2022-10-17 205400
Screenshot 2022-10-17 205445
Screenshot 2022-10-17 205616
Screenshot 2022-10-17 205548

**Comment by olale013** [comment]
@caljay98 How picky do we want to be with this? Hopefully won't even be needed with the new design.

**Comment by caljay98** [comment]
I think it's fine to have a few points that are missed, and adding checksums will remove this issue so it's not worth worrying too much about it

**Review by caljay98 — APPROVED** [review]
Looks great

**Pull request merged**
